### ISSUE TITLE
Support SourceLink.GitHub

### ISSUE THREAD

**Issue by alefcarlos** [wittylion/AutoPipe#1]
Thank you for this lib ! It is awesome !

It would be cool it supports [SourceLink](https://github.com/dotnet/sourcelink) to allow us to debug our pipeline flows.

I can make a PR ;)

**Comment by SergAtGitHub** [comment]
Hello @alefcarlos 

Glad to hear that you like the lib :)
I took a look at the link that you sent me, already applied changes, gonna test it today and then publish with a small new feature.
Thanks for the suggestion, appreciate it 👍 
I will leave a comment and close this issue when the new version is on NuGet.

**Comment by SergAtGitHub** [comment]
@alefcarlos

[New version](https://www.nuget.org/packages/Pipelines.Net/) is available on NuGet. Also [debug symbols](https://www.nuget.org/api/v2/symbolpackage/Pipelines.Net/1.1.7) attached to the package page and can be downloaded.

I was able to debug code with "nuget.org" package source turned on in Visual Studio. But it's still a bit hard to debug pipeline runner execution and dynamic processors created with ActionProcessor. Anyway, it is good to know that I can improve some things a bit :)

If you need more help with this lib, just let me know, will be glad to help you.
